### ISSUE TITLE
replacementFile.json is empty

### ISSUE THREAD

**Issue by donhill** [moshbit/Kotlift#11]
It seems that is the replacementFile.json isn't in the format where one object is on each line then loadReplacements fails with replacementFile is empty.

I have to format the file like {"from": "val", "to": "let","multiple": true} in order for the loading of the replacement to succeed. 

I think maybe we can just create an poko and something like jackson and gson to deserialize.

**Comment by vonox7** [comment]
Of course, feel free to create a pull request.

**Comment by ivanatshoal** [comment]
tried fixing this myself but the language is not known to me very well, has this issue been resolved or been pushed anywhere? its blocking and In mlearning but seems like a quick fix. do i just have to 'format the file' in some way? all on one line?

**Comment by cmoine** [comment]
I created a PR for this: https://github.com/moshbit/Kotlift/pull/14

**Comment by vonox7** [comment]
Thanks @cmoine for the fix!

**Comment by unkadoug** [comment]
I still see this issue.  I just cloned Kotlift, ran the 'java -jar ...' command from the README, and got the same error message.  I installed gradle, hoping that I could use it to rebuild a possibly-stale moshbit.kotlift.jar file, but I haven't found a way to rebuild the moshbit file.

**Comment by SylvainHocq** [comment]
Idem for me ,  I just cloned Kotlift, ran the 'java -jar ...' command from the README, and got the same error message.

**Comment by SylvainHocq** [comment]
i try the solution of @donhill and it work directly with the jar file .
This is the correct format for replacementFile.json
<span>
[
{"from": "val","to": "let","multiple": true},
{"from": "null","to": "nil","multiple": true},
{"from": "this","to": "self","multiple": true},
{"from": "Unit","to": "Void","multiple": true},
{"from": "Boolean","to": "Bool","multiple": true},
{"from": "Float","to": "Double","multiple": true},
{"from": "Long","to": "Int64","multiple": true},
{"from": "Int","to": "Int32","multiple": true},
{"from": "Short","to": "Int16","multiple": true},
{"from": "Byte","to": "Int8","multiple": true},
{"from": "println","to": "print","multiple": true},
{"from": "print\\(\\)","to": "print(\"\")","multiple": true},
{"from": "interface","to": "protocol","multiple": true},
{"from": "get\\(\\)","to": "get","multiple": true},
{"from": "protected","to": "internal","multiple": true},
{"from": "Collection","to": "Array","multiple": true},
{"from": ".invoke","to": "","multiple": true}
]
</span>
